const domain = 'gooseadmin'

export const baseURL = 'https://www.gooseadmin.com/gooseApp/'
export const mediaURL = 'https://www.gooseadmin.com/media/'
export const fetchTokenURL = 'https://www.gooseadmin.com/gooseApp/token/'
export const registerURL = 'https://www.gooseadmin.com/gooseApp/register/'
export const fetchUserURL = 'https://www.gooseadmin.com/gooseApp/update/'
export const searchUserURL = 'https://www.gooseadmin.com/gooseApp/search/'
export const leaderBoardURL = 'https://www.gooseadmin.com/gooseApp/leaderboard/'
export const fetchMessagesURL = 'https://www.gooseadmin.com/gooseApp/messages/'